# Generated by Django 4.1.3 on 2022-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('mobno', models.CharField(max_length=255)),
                ('peremail', models.EmailField(max_length=254)),
                ('iitbemail', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('verified', models.BooleanField()),
            ],
        ),
    ]
